keys:
  - &admin_nalon age1qg6pzdtg3ezq2mk59ghmd7uc5gyyuwws34m2am9a33kqfahdjscszj2s54
  - &host_vm age1nq4u292y8qkmc0rgchgk9z5mgt7j8m5l6v0yzw923fw3ghtnp5fsdytggj

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin_nalon
          - *host_vm
